# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\rcryptoservice\",\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05senha\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"c\n\x0fRegisterRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0b\n\x03\x63pf\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x61ta_nascimento\x18\x04 \x01(\t\x12\r\n\x05senha\x18\x05 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"k\n\x10\x42uyCryptoRequest\x12\x13\n\x0b\x63\x61rteira_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63riptomoeda_id\x18\x02 \x01(\t\x12\x12\n\nquantidade\x18\x03 \x01(\x02\x12\x16\n\x0epreco_unitario\x18\x04 \x01(\x02\"$\n\x11\x42uyCryptoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"&\n\x0fUserInfoRequest\x12\x13\n\x0b\x63\x61rteira_id\x18\x01 \x01(\t\"f\n\x10UserInfoResponse\x12$\n\x06moedas\x18\x01 \x03(\x0b\x32\x14.cryptoservice.Moeda\x12,\n\ntransacoes\x18\x02 \x03(\x0b\x32\x18.cryptoservice.Transacao\"9\n\x05Moeda\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x12\n\nquantidade\x18\x02 \x01(\x02\x12\x0e\n\x06imagem\x18\x03 \x01(\t\"L\n\tTransacao\x12\r\n\x05moeda\x18\x01 \x01(\t\x12\x0e\n\x06imagem\x18\x02 \x01(\t\x12\x12\n\nquantidade\x18\x03 \x01(\x02\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\"\x16\n\x14\x43olaboradoresRequest\"(\n\x15\x43olaboradoresResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa3\x03\n\rCryptoService\x12\x42\n\x05Login\x12\x1b.cryptoservice.LoginRequest\x1a\x1c.cryptoservice.LoginResponse\x12K\n\x08Register\x12\x1e.cryptoservice.RegisterRequest\x1a\x1f.cryptoservice.RegisterResponse\x12N\n\tBuyCrypto\x12\x1f.cryptoservice.BuyCryptoRequest\x1a .cryptoservice.BuyCryptoResponse\x12N\n\x0bGetUserInfo\x12\x1e.cryptoservice.UserInfoRequest\x1a\x1f.cryptoservice.UserInfoResponse\x12\x61\n\x14MostrarColaboradores\x12#.cryptoservice.ColaboradoresRequest\x1a$.cryptoservice.ColaboradoresResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=32
  _globals['_LOGINREQUEST']._serialized_end=76
  _globals['_LOGINRESPONSE']._serialized_start=78
  _globals['_LOGINRESPONSE']._serialized_end=108
  _globals['_REGISTERREQUEST']._serialized_start=110
  _globals['_REGISTERREQUEST']._serialized_end=209
  _globals['_REGISTERRESPONSE']._serialized_start=211
  _globals['_REGISTERRESPONSE']._serialized_end=246
  _globals['_BUYCRYPTOREQUEST']._serialized_start=248
  _globals['_BUYCRYPTOREQUEST']._serialized_end=355
  _globals['_BUYCRYPTORESPONSE']._serialized_start=357
  _globals['_BUYCRYPTORESPONSE']._serialized_end=393
  _globals['_USERINFOREQUEST']._serialized_start=395
  _globals['_USERINFOREQUEST']._serialized_end=433
  _globals['_USERINFORESPONSE']._serialized_start=435
  _globals['_USERINFORESPONSE']._serialized_end=537
  _globals['_MOEDA']._serialized_start=539
  _globals['_MOEDA']._serialized_end=596
  _globals['_TRANSACAO']._serialized_start=598
  _globals['_TRANSACAO']._serialized_end=674
  _globals['_COLABORADORESREQUEST']._serialized_start=676
  _globals['_COLABORADORESREQUEST']._serialized_end=698
  _globals['_COLABORADORESRESPONSE']._serialized_start=700
  _globals['_COLABORADORESRESPONSE']._serialized_end=740
  _globals['_CRYPTOSERVICE']._serialized_start=743
  _globals['_CRYPTOSERVICE']._serialized_end=1162
# @@protoc_insertion_point(module_scope)
